export const district = {
    'Phra Nakhon': 'พระนคร',
    'Dusit': 'ดุสิต',
    'Nong Chok': 'หนองจอก',
    'Bang Rak': 'บางรัก',
    'Bang Khen': 'บางเขน',
    'Bang Kapi': 'บางกะปิ',
    'Pathum Wan': 'ปทุมวัน',
    'Pom Prap Sattru Phai': 'ป้อมปราบศัตรูพ่าย',
    'Phra Khanong': 'พระโขนง',
    'Min Buri': 'มีนบุรี',
    'Lat Krabang': 'ลาดกระบัง',
    'Yan Nawa': 'ยานนาวา',
    'Samphanthawong': 'สัมพันธวงศ์',
    'Phaya Thai': 'พญาไท',
    'Thon Buri': 'ธนบุรี',
    'Bangkok Yai': 'บางกอกใหญ่',
    'Huai Khwang': 'ห้วยขวาง',
    'Khlong San': 'คลองสาน',
    'Taling Chan': 'ตลิ่งชัน',
    'Bangkok Noi': 'บางกอกน้อย',
    'Bang Khun Thian': 'บางขุนเทียน',
    'Phasi Charoen': 'ภาษีเจริญ',
    'Nong Khaem': 'หนองแขม',
    'Rat Burana': 'ราษฎร์บูรณะ',
    'Bang Phlat': 'บางพลัด',
    'Din Daeng': 'ดินแดง',
    'Bueng Kum': 'บึงกุ่ม',
    'Sathon': 'สาทร',
    'Bang Sue': 'บางซื่อ',
    'Chatuchak': 'จตุจักร',
    'Bang Kho Laem': 'บางคอแหลม',
    'Prawet': 'ประเวศ',
    'Khlong Toei': 'คลองเตย',
    'Suan Luang': 'สวนหลวง',
    'Chom Thong': 'จอมทอง',
    'Don Mueang': 'ดอนเมือง',
    'Ratchathewi': 'ราชเทวี',
    'Lat Phrao': 'ลาดพร้าว',
    'Watthana': 'วัฒนา',
    'Bang Khae': 'บางแค',
    'Lak Si': 'หลักสี่',
    'Sai Mai': 'สายไหม',
    'Khan Na Yao': 'คันนายาว',
    'Saphan Sung': 'สะพานสูง',
    'Wang Thonglang': 'วังทองหลาง',
    'Khlong Sam Wa': 'คลองสามวา',
    'Bang Na': 'บางนา',
    'Thawi Watthana': 'ทวีวัฒนา',
    'Thung Khru': 'ทุ่งครุ',
    'Bang Bon': 'บางบอน'
}